name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install 
      - name: Lint files
        working-directory: ./frontend
        run: npm run lint
      - name: Run prettier lint
        working-directory: ./frontend
        run: npm run prettier --write .
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install 
      - name: Build project
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_CONTENTFUL_API_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_API_TOKEN }}
          NEXT_PUBLIC_CONTENTFUL_API_SPACE: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_API_SPACE }}
          NEXT_PUBLIC_CONTENTFUL_HOST: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_HOST }}
          NEXT_PUBLIC_CONTENTFUL_ENVRIONMENT: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ENVRIONMENT }}
          NEXT_PUBLIC_CONTENTFUL_MANAGEMENT_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_MANAGEMENT_TOKEN }}
          NEXT_PUBLIC_EMAILJS_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_ID }}
          NEXT_PUBLIC_TEMPLATE: ${{ secrets.NEXT_PUBLIC_TEMPLATE }}
          NEXT_PUBLIC_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_SERVICE_ID }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          NEXT_PUBLIC_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_MEASUREMENT_ID }}
          NEXT_PUBLIC_MAILCHIMP_URL: ${{ secrets.NEXT_PUBLIC_MAILCHIMP_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: npm run build